api:
  id: "20882736"

salesforce-sapi:
  host: "caminho-salesforce-sapi-qa-e7hhs6.f12twh.usa-e2.cloudhub.io"
  port: "443"
  timeout: "30000"

dealernet-sapi:
  host: "caminho-dealernet-sapi-qa-e7hhs6.f12twh.usa-e2.cloudhub.io"
  port: "443"
  timeout: "30000"
  basePath: "/api"
