salesforce-sapi:
  client_id: "![mii1WV3g93XO6rZyL7QbmMWT1wc7n0AhFGe69mQST7cqpRLAIoGYvg==]"
  client_secret: "![HxmvpbL6t6ybO4rjt9Hl4c4VdUbVJaTVPVvdbytASxT5nCQUMy6/gg==]"

dealernet-sapi:
  client_id: "![mii1WV3g93XO6rZyL7QbmMWT1wc7n0AhFGe69mQST7cqpRLAIoGYvg==]"
  client_secret: "![HxmvpbL6t6ybO4rjt9Hl4c4VdUbVJaTVPVvdbytASxT5nCQUMy6/gg==]"